### ISSUE TITLE
Package is not working

### ISSUE THREAD

**Issue by yashwp** [baranyildirim/google_pay#3]
There is no documentation for the usage. I have used your example application code. I'm getting errors as show blow.

**As soon as the app rebuilds, this is the error prompting**
```
E/flutter (25998): [ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: MissingPluginException(No implementation found for method getPlatformVersion on channel google_pay)
E/flutter (25998): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:159:7)
E/flutter (25998): <asynchronous suspension>
E/flutter (25998): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:334:12)
E/flutter (25998): #2      GooglePay.platformVersion (package:google_pay/google_pay.dart:91:37)
E/flutter (25998): #3      _HomeScreenState.initPlatformState (package:stack_app/modules/home/home_screen.dart:34:41)
E/flutter (25998): #4      _HomeScreenState.initState (package:stack_app/modules/home/home_screen.dart:26:5)
E/flutter (25998): #5      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4684:58)
E/flutter (25998): #6      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4520:5)
E/flutter (25998): #7      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490:14)
E/flutter (25998): #8      MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5991:32)
```

**I anyways went ahead _(which doesn't make sense after the above error)_ I pressed the button to invoke the `openGooglePaySetup` it throws below error.** 

```
E/flutter (25998): [ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: MissingPluginException(No implementation found for method openGooglePaySetup on channel google_pay)
E/flutter (25998): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:159:7)
E/flutter (25998): <asynchronous suspension>
E/flutter (25998): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:334:12)
E/flutter (25998): #2      GooglePay.openGooglePaySetup (package:google_pay/google_pay.dart:37:22)
E/flutter (25998): #3      _HomeScreenState.onButtonPressed (package:stack_app/modules/home/home_screen.dart:83:23)
E/flutter (25998): #4      _HomeScreenState.build.<anonymous closure> (package:stack_app/modules/home/home_screen.dart:69:19)
E/flutter (25998): #5      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:992:19)
E/flutter (25998): #6      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:1098:38)
E/flutter (25998): #7      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:184:24)
E/flutter (25998): #8      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:524:11)
E/flutter (25998): #9      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:284:5)
E/flutter (25998): #10     BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:219:7)
E/flutter (25998): #11     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:477:9)
E/flutter (25998): #12     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:78:12)
E/flutter (25998): #13     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:124:9)
E/flutter (25998): #14     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:377:8)
E/flutter (25998): #15     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:122:18)
E/flutter (25998): #16     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:108:7)
E/flutter (25998): #17     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:220:19)
E/flutter (25998): #18     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:200:22)
E/flutter (25998): #19     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:158:7)
E/flutter (25998): #20     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:104:7)
E/flutter (25998): #21     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:88:7)
E/flutter (25998): #22     _rootRunUnary (dart:async/zone.dart:1206:13)
E/flutter (25998): #23     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
E/flutter (25998): #24     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
E/flutter (25998): #25     _invoke1 (dart:ui/hooks.dart:267:10)
E/flutter (25998): #26     _dispatchPointerDataPacket (dart:ui/hooks.dart:176:5)
E/flutter (25998): 
```

Why would you host a package when it not working at all?

**Comment by baranyildirim** [comment]
The package needs to be updated. It is open source and I develop it on my own time. If it does not work, or you do not like it then don't use it.
